import google from "@/data/google.json";
import meta from "@/data/meta.json";
import msci from "@/data/msci.json";
import spgi from "@/data/spgi.json";
import cat from "@/data/cat.json";

export type KPI = {
  /** Short acronym/badge displayed first (e.g. "DAP", "Cloud Rev"). */
  short: string;
  /**
   * ISO date string of the most recent data point (e.g. "2025-12-31").
   * Used to flag stale data with a freshness warning. Optional for backwards
   * compat; if missing we fall back to "unknown" indicator.
   */
  last_data_date?: string;
  /** French name (full). */
  name_fr: string;
  /** Original English name (kept under FR). Optional if FR == EN. */
  name_en?: string;
  /** Italic 1-line explanation: precise scope (which segment, which products, etc.). */
  explanation: string;
  value: string;
  unit: string;
  yoy: string;
  type: string;
  nature: string;
  comparable: string;
  /** Comparability key: KPIs sharing the same key across companies are auto-matched in Compare. */
  compare_key?: string;
  signal: string;
  description: string;
  history: number[];
  /**
   * KPI tags pour l'organisation Hero / Indicateurs clés / Stories.
   * DÉCIDÉS UNE FOIS pour toutes au moment de la publication de la société.
   * Ne changent PAS quand de nouvelles données trimestrielles arrivent.
   * Voir CLAUDE.md § "ORDRE D'AFFICHAGE DES KPI".
   */
  /** Distinctif, propre à la société ou à sa sous-industrie (DAP, Carnet, Ratings Cyclique). */
  is_wow?: boolean;
  /** Comptable banal (Total Revenue, Net Income, EPS, Operating Margin, Capex, FCF). */
  is_generic?: boolean;
  /**
   * Historique <5 ans → bouge dans le bloc Stories (pas Indicateurs clés).
   * Aussi true si KPI ponctuel (publié 1 fois lors d'un investor day).
   */
  is_short_history?: boolean;
  /** Catégorie de la story. Ex: "Innovation", "Marché", "Adoption", "Capacité". */
  story_category?: string;
  /**
   * TTM = Trailing Twelve Months. Somme des 4 derniers trimestres dispo
   * (Q2 N-1 + Q3 N-1 + Q4 N-1 + Q1 N). Affiché sur les charts comme une
   * barre / point supplémentaire APRÈS la dernière année calendaire,
   * avec un style visuel distinct (couleur plus claire / pointillé) pour
   * qu'on comprenne que c'est "12 derniers mois" et pas une année calendaire.
   * Optionnel : non rendu si absent ou null.
   */
  ttm?: number | null;
};

export type Ranks = {
  global_world: string; // e.g. "#4"
  global_us: string;
  sector: string;
  subsector: string;
};

/** Market position: company segment revenue vs total addressable market. */
/** Tranche d'une répartition (géographique ou par segment opérationnel). */
export type RevenueSlice = {
  /** Libellé en FR. */
  label: string;
  /** Libellé en EN (optionnel, fallback sur label). */
  label_en?: string;
  /** Valeur dans l'unité de la breakdown (montant ou %). */
  value: number;
  /** Couleur custom (sinon palette auto). */
  color?: string;
};

/** Répartition du chiffre d'affaires par dimension (géo, segment, etc.). */
export type RevenueBreakdown = {
  /** "$B", "$M", "%", etc. Si "%", values doivent sommer à ~100. */
  unit: string;
  /** Total explicite (sinon = somme des slices). */
  total?: number;
  slices: RevenueSlice[];
  /** Date de référence des chiffres (ex: "2024-12-31"). */
  source_date?: string;
  /** Source courte (ex: "10-K 2024"). */
  source?: string;
};

export type MarketPosition = {
  segment_name: string;
  /** Company revenue on that segment, in the same unit as `segment_unit`. */
  segment_revenue: number;
  segment_unit: string; // "$B", "$M"
  /** Total Addressable Market (point estimate). */
  tam: number;
  tam_unit: string;
  /** Optional TAM range for honest uncertainty display. */
  tam_range?: [number, number];
  /** Source short name + year, e.g. "Gartner, 2025". */
  source: string;
  /** Longer methodological note shown in the "i" tooltip. */
  source_note?: string;
  /** Optional expected market CAGR %, shown as comparison to company CAGR. */
  market_cagr?: number;
};

export type RiskCategory =
  | "regulatory"
  | "competitive"
  | "cyber"
  | "operational"
  | "financial"
  | "macro"
  | "technology";

export type RiskTrend = "new" | "up" | "stable" | "down" | "removed";

export type CompanyRisk = {
  /** Editorial short title in French (8-14 words). */
  title: string;
  /** Editorial title in English (V2 = auto-generated by Groq pipeline). */
  title_en?: string;
  category: RiskCategory;
  /** Original 10-K quote (verbatim from SEC filing, English). */
  quote: string;
  /** French translation of the 10-K quote. */
  quote_fr?: string;
  /** Trend vs the prior-year 10-K. */
  trend: RiskTrend;
  /** Severity score 1-5 where 5 = most severe. */
  score: 1 | 2 | 3 | 4 | 5;
  /**
   * Rationale for the score, shown in an "i" tooltip.
   * Should cite the 4 inputs: position in 10-K, language intensity,
   * trend vs prior year, category weight.
   */
  score_rationale: string;
};

export type HolderType = "institutionnel" | "particulier" | "insider" | "fondateur" | "fonds souverain";

export type Shareholder = {
  name: string;
  stake_pct: number;
  type: HolderType;
  /** If insider, the role (e.g. "CEO", "Fondateur", "Co-fondateur"). */
  role?: string;
};

/** Peer benchmark hint for a metric. */
export type PeerRank = "bas" | "moyen" | "haut" | "extrême";

/** Governance & executive compensation from the latest annual shareholders meeting. */
export type Governance = {
  /** Date of the last annual shareholders meeting, e.g. "2025-06-10". */
  agm_date: string;
  /** Fiscal year the numbers correspond to. */
  fiscal_year: number;
  /** CEO name. */
  ceo_name: string;
  /** CEO total compensation (cash + stock + perks), in $M. */
  ceo_total_comp_m: number;
  /** Peer rank for this metric (sector median). */
  ceo_comp_rank?: PeerRank;
  /** CEO compensation as a multiple of median employee pay. */
  ceo_pay_ratio: number;
  ceo_pay_ratio_rank?: PeerRank;
  /** Shareholder approval % on executive compensation vote (formerly "say-on-pay"). */
  exec_comp_approval_pct: number;
  exec_comp_approval_rank?: PeerRank;
  /** % of independent directors on the board. */
  board_independence_pct: number;
  board_independence_rank?: PeerRank;
  /** Number of directors. */
  board_size: number;
  /** Average tenure of directors, in years. */
  avg_tenure_years: number;
  /** % of women on the board. */
  board_women_pct?: number;
  /** Average age of directors. */
  avg_board_age?: number;
  /** Total insider ownership % (directors + officers combined). */
  insider_ownership_pct?: number;
  /** Dual-class / voting structure description. */
  voting_structure?: string;
  /** Board members (name + role). */
  directors?: Array<{ name: string; role: string }>;
  /** Top 3 voting rights holders. */
  top_voting?: Shareholder[];
  /** Top 3 capital holders (by economic ownership). */
  top_capital?: Shareholder[];
  /** Free-form notable governance items. */
  notes?: string[];
};

/** Company AI positioning — sourced from 10-K, 10-Q, and investor communications. */
export type AIPositioning = {
  /** Overall stance: "leader" | "integrator" | "cautious" | "absent". */
  stance: "leader" | "integrator" | "cautious" | "absent";
  /** 2-4 sentence summary of how the company positions itself on AI. */
  summary: string;
  /** 3-5 concrete examples of AI uses / products / investments. */
  evidence: string[];
  /** Source document cited (e.g. "10-K 2024", "Earnings Call Q4 2025"). */
  source: string;
};

export type Company = {
  ticker: string;
  name: string;
  sector: string;
  subsector: string;
  hero_kpi: string; // matches KPI.short
  /**
   * Rationale (1-2 phrases) expliquant POURQUOI ce KPI a été choisi comme
   * Hero pour cette société. Lu lors de l'audit éditorial. Pas affiché à
   * l'utilisateur final (sauf en mode debug). Voir CLAUDE.md § ORDRE.
   */
  hero_kpi_rationale?: string;
  tagline: string;
  founded: number;
  ipo: number;
  ranks: Ranks;
  /** Logo treatment hint per company (used to choose visual signature in V1). */
  logo_treatment: "orbit" | "prism" | "ring" | "wave" | "spark";
  kpis: KPI[];
  /**
   * Optional market positions: one per segment where both company revenue
   * and a credible TAM are available. Not shown if missing (honesty rule).
   */
  market_positions?: MarketPosition[];
  /** Répartition du chiffre d'affaires par zone géographique. */
  revenue_by_geography?: RevenueBreakdown;
  /** Répartition du chiffre d'affaires par segment opérationnel. */
  revenue_by_segment?: RevenueBreakdown;
  /** Top 5-8 risks extracted from latest 10-K. */
  risks?: CompanyRisk[];
  /** AI positioning statement. Mandatory for V1 — if no mention, stance = "absent". */
  ai_positioning?: AIPositioning;
  /** Governance / executive compensation from DEF 14A. */
  governance?: Governance;
  /**
   * Profit warning history + forward-looking risk score.
   * Score (1-5) calé sur :
   *   1) historique des PW + commentaires direction + dernier earnings call
   *   2) tendance court+moyen terme (<3 mois) de réduction de marges au-delà
   *      des déclarations publiques précédentes
   */
  profit_warning?: ProfitWarning;
  /**
   * Date approximative des prochains résultats (ISO ou texte). Affichée
   * dans la tooltip "à jour" sous la forme "~ [date]".
   */
  next_earnings_date?: string;
};

export type ProfitWarning = {
  /** ISO date du dernier profit warning, null si jamais. */
  last_date: string | null;
  /** 1 = très peu probable, 5 = imminent. */
  score: 1 | 2 | 3 | 4 | 5;
  /** Justification de la note : historique + commentaires direction + signaux. */
  rationale: string;
  /** Commentaire optionnel sur la trajectoire de marges <3 mois. */
  margin_trend?: string;
};

// META en 1er = société par défaut (fallback partout où une sté doit
// être chargée sans contexte). Ordre = ordre d'affichage des cards home.
export const COMPANIES: Record<string, Company> = {
  META: meta as Company,
  GOOGL: google as Company,
  MSCI: msci as Company,
  SPGI: spgi as Company,
  CAT: cat as Company,
};

export const TICKERS = Object.keys(COMPANIES);

/**
 * Alias multi-classes : certaines sociétés cotent plusieurs lignes (ex.
 * Alphabet : GOOGL Class A avec droit de vote, GOOG Class C sans). On
 * résout vers le ticker canonique du panel pour qu'une recherche ou une
 * URL avec l'alias retombe sur la bonne fiche, et que les pages dual-
 * class ne soient pas dupliquées.
 *
 * Étendre cette table à mesure que de nouvelles sociétés sont ajoutées
 * (BRK.A/BRK.B, FOX/FOXA, NWS/NWSA, DISCA/DISCK, etc.).
 */
export const TICKER_ALIASES: Record<string, string> = {
  GOOG: "GOOGL",
};

/** Renvoie le ticker canonique (majuscules), résout les alias. */
export function canonicalTicker(input: string): string {
  const u = input.toUpperCase();
  return TICKER_ALIASES[u] ?? u;
}

export function getCompany(ticker: string): Company | null {
  return COMPANIES[canonicalTicker(ticker)] ?? null;
}

export function getHero(company: Company): KPI {
  return (
    company.kpis.find((k) => k.short === company.hero_kpi) ?? company.kpis[0]
  );
}

/* -------------------------------------------------------------------------- */
/*                              Format helpers                                */
/* -------------------------------------------------------------------------- */

/** Convert "$B" → "Mds $", "B" → "Mds", "$M" → "M $", "%" → "%", etc. */
export function formatUnit(unit: string): string {
  switch (unit) {
    case "$B":
      return "Mds $";
    case "B":
      return "Mds";
    case "$M":
      return "M $";
    case "M":
      return "M";
    case "% YoY":
      return "%";
    default:
      return unit;
  }
}

/**
 * Format compact pour le hero number :
 *   - 2 décimales max
 *   - Auto-conversion M → Mds quand |valeur| >= 1000
 *   - locale FR (espace comme séparateur milliers)
 *
 * Évite que le chiffre + unité passe sur 2 lignes quand la colonne hero
 * est étroite (cas "3,302 M $" → "3,3 Mds $" plus court).
 */
export function formatHeroValue(value: string, unit: string): { value: string; unit: string } {
  const cleaned = value.replace(/,/g, "").trim();
  const num = parseFloat(cleaned);
  if (!Number.isFinite(num)) {
    return { value, unit: formatUnit(unit) };
  }

  let displayNum = num;
  let displayUnit = formatUnit(unit);

  if ((unit === "M" || unit === "$M") && Math.abs(num) >= 1000) {
    displayNum = num / 1000;
    displayUnit = unit === "$M" ? "Mds $" : "Mds";
  }

  const formatted = displayNum.toLocaleString("fr-FR", {
    maximumFractionDigits: 2,
  });
  return { value: formatted, unit: displayUnit };
}

/** Whether the YoY string already starts with sign. */
export function ensureYoYSuffix(yoy: string): string {
  // strip parenthetical " (YoY)" if already present
  return yoy.trim();
}

/**
 * Freshness tier for a piece of data based on its last_data_date.
 *  - "fresh" : < 4 months (last quarter)
 *  - "recent" : 4–12 months (last fiscal year still relevant)
 *  - "stale" : > 12 months (warn user)
 *  - "unknown" : no date
 */
export type FreshnessTier = "fresh" | "recent" | "stale" | "unknown";

export function getFreshness(lastDate?: string, now: Date = new Date()): FreshnessTier {
  if (!lastDate) return "unknown";
  const d = new Date(lastDate);
  if (Number.isNaN(d.getTime())) return "unknown";
  const months = (now.getTime() - d.getTime()) / (1000 * 60 * 60 * 24 * 30.4);
  if (months < 4) return "fresh";
  if (months < 12) return "recent";
  return "stale";
}

/**
 * Compound annual growth rate over the full history window.
 * Returns null when not meaningful (any zero/negative endpoint, < 2 points,
 * or KPIs that already are themselves growth rates like "% YoY").
 */
export function cagr(history: number[], unit?: string): number | null {
  if (unit === "% YoY") return null; // already a growth-of-growth → meaningless
  if (!history || history.length < 2) return null;
  const first = history[0];
  const last = history[history.length - 1];
  if (first <= 0 || last <= 0) return null;
  const periods = history.length - 1;
  return (Math.pow(last / first, 1 / periods) - 1) * 100;
}

/** Format CAGR for display, e.g. "+22.4 % / an" or null when N/A. */
export function formatCAGR(history: number[], unit?: string): string | null {
  const c = cagr(history, unit);
  if (c === null) return null;
  const sign = c > 0 ? "+" : "";
  return `${sign}${c.toLocaleString("fr-FR", {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  })} % / an`;
}

/* -------------------------------------------------------------------------- */
/*                              Interpretation                                */
/* -------------------------------------------------------------------------- */

export type InterpretTone = "pos" | "neg" | "neutral" | "future";

export type InterpretBullet = {
  label: string;
  body: string;
  tone: InterpretTone;
};

export type InterpretBlock = {
  /** Headline sentence (HTML allowed). */
  lead: string;
  /** Structured bullets, including the future-watch one as its own bullet. */
  bullets: InterpretBullet[];
};

export function interpretStructured(company: Company): InterpretBlock {
  const hero = getHero(company);
  // Préférer un KPI sectoriel (Demand/User/Adoption) plutôt que le total revenu
  // pour le bloc "Moteur de croissance" — le revenu n'est pas un moteur,
  // c'est un résultat. Fallback sur Revenue uniquement si aucun segment dispo.
  const segmentDrivers = company.kpis.filter((k) =>
    ["Demand", "User", "Adoption"].includes(k.type)
  );
  const revenueDrivers = company.kpis.filter((k) => k.type === "Revenue");
  const driver =
    segmentDrivers.find((d) => d.short !== hero.short) ??
    revenueDrivers.find((d) => d.short !== hero.short) ??
    segmentDrivers[0];
  const risk = company.kpis.find(
    (k) =>
      (k.type === "Cost" && !k.yoy.startsWith("-")) ||
      (k.type === "Margin" && k.yoy.startsWith("-"))
  );
  const cash = company.kpis.find((k) => k.type === "Cash");

  const lead = `Le KPI principal de <strong>${company.name}</strong> est <strong>${hero.name_fr}</strong>, à <strong>${hero.value} ${formatUnit(hero.unit)}</strong> (${hero.yoy} <em>YoY</em>). À retenir : <em>${hero.signal.toLowerCase()}</em>.`;

  const bullets: InterpretBullet[] = [];
  if (driver && driver.short !== hero.short) {
    bullets.push({
      label: "Moteur de croissance",
      body: `<strong>${driver.name_fr}</strong> à ${driver.value} ${formatUnit(driver.unit)} (${driver.yoy}). ${driver.signal}.`,
      tone: "pos",
    });
  }
  if (risk) {
    bullets.push({
      label: "Point de vigilance",
      body: `<strong>${risk.name_fr}</strong> à ${risk.value} ${formatUnit(risk.unit)} (${risk.yoy}). ${risk.signal}.`,
      tone: "neg",
    });
  }
  if (cash && cash.short !== hero.short) {
    bullets.push({
      label: "Génération de cash",
      body: `<strong>${cash.name_fr}</strong> à ${cash.value} ${formatUnit(cash.unit)} (${cash.yoy}). ${cash.signal}.`,
      tone: "neutral",
    });
  }

  // FUTURE bullet — promoted to first-class citizen.
  bullets.push({
    label: "À surveiller prochainement",
    body: `Trois scénarios possibles pour <strong>${hero.name_fr}</strong> : (1) <strong>accélération</strong> qui validerait le momentum, (2) <strong>stabilisation</strong> autour du niveau actuel, (3) <strong>retournement</strong> qui casserait la tendance. Le marché ajustera la valorisation en fonction du scénario observé.`,
    tone: "future",
  });

  return { lead, bullets };
}

/* -------------------------------------------------------------------------- */
/*                            Compare matching                                */
/* -------------------------------------------------------------------------- */

/**
 * Find companies that share at least one comparable KPI with the source company.
 * Returns map: ticker → { company, matchedKpi, sourceKpi } sorted by relevance.
 */
export function findComparable(sourceTicker: string, sourceKpiShort?: string) {
  const src = COMPANIES[sourceTicker];
  if (!src) return [];
  const srcKpi = src.kpis.find((k) => k.short === sourceKpiShort);

  const matches: Array<{
    ticker: string;
    company: Company;
    matchedKpi: KPI;
    matchedSourceKpi: KPI;
    score: number; // higher = more relevant
  }> = [];

  for (const t of TICKERS) {
    if (t === sourceTicker) continue;
    const c = COMPANIES[t];
    // Try to match source KPI first
    if (srcKpi?.compare_key) {
      const m = c.kpis.find((k) => k.compare_key === srcKpi.compare_key);
      if (m) {
        matches.push({
          ticker: t,
          company: c,
          matchedKpi: m,
          matchedSourceKpi: srcKpi,
          score: 100,
        });
        continue;
      }
    }
    // Fallback: any shared compare_key
    const sharedKeys = src.kpis
      .map((k) => k.compare_key)
      .filter((x): x is string => Boolean(x));
    let bestPair: { src: KPI; m: KPI } | null = null;
    for (const k of sharedKeys) {
      const a = src.kpis.find((x) => x.compare_key === k);
      const b = c.kpis.find((x) => x.compare_key === k);
      if (a && b) {
        bestPair = { src: a, m: b };
        break;
      }
    }
    if (bestPair) {
      matches.push({
        ticker: t,
        company: c,
        matchedKpi: bestPair.m,
        matchedSourceKpi: bestPair.src,
        score: 50,
      });
    }
    // If no shared key at all, don't include this company
  }

  return matches.sort((a, b) => b.score - a.score);
}

/**
 * True si la source indiquée provient d'un document officiel de la sté
 * (10-K, 10-Q, 8-K, DEF 14A, Earnings Release/Call, Investor Day, Investor
 * Deck, etc.). Dans ce cas l'app n'affiche PAS la source à l'utilisateur :
 * c'est implicite que la donnée vient des filings officiels Mettrik.
 */
export function isOfficialSource(s?: string | null): boolean {
  if (!s) return false;
  const u = s.toUpperCase();
  const keywords = [
    "10-K", "10-Q", "8-K", "DEF 14A", "EARNINGS",
    "INVESTOR DAY", "INVESTOR DECK", "PROXY", "ANNUAL REPORT",
  ];
  return keywords.some((k) => u.includes(k));
}
