import json, os

SIGN = "CONV-SUBAGENT-RISKS-BATCH062-2026-05-30"

def mk(title, cat, sev, rationale, trend, summary):
    return {
        "title": title,
        "category": cat,
        "severity": sev,
        "score_rationale": rationale,
        "trend": trend,
        "summary": summary,
    }

R_MAT = "Sévérité {n}/5 : la société utilise l'expression \"material adverse effect\" indiquant un impact potentiel matériel sur résultats ou situation financière."
R_GEN = "Sévérité {n}/5 : risque mentionné dans Item 1A Risk Factors sans qualification d'intensité spécifique."
R_EU  = "Sévérité {n}/5 : risque identifié dans la section Risk Management du Rapport Annuel."

DATA = {
    "ULTA": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-03-27 (exercice clos février 2025)",
        "risks": [
            mk("Concurrence et fragmentation de la distribution beauté", "competitive", 3,
               R_MAT.format(n=3), "deteriorating",
               "Pression concurrentielle accrue dans la beauté prestige et de masse : grands magasins, pure players e-commerce et chaînes spécialisées érodent la part de marché et la fréquentation des magasins physiques."),
            mk("Dépendance aux marques fournisseurs clés", "operational", 3,
               R_MAT.format(n=3), "stable",
               "Concentration sur un nombre limité de marques exclusives ou prestige : perte d'un partenariat majeur ou changement de canal de distribution pénaliserait l'assortiment et les ventes."),
            mk("Comportement de consommation et environnement macro", "macro", 3,
               R_MAT.format(n=3), "deteriorating",
               "Sensibilité de la demande beauté discrétionnaire à l'inflation, à la confiance des ménages et à la baisse de fréquentation des centres commerciaux où Ulta est implantée."),
            mk("Réputation de marque et sécurité produit", "reputational", 2,
               R_GEN.format(n=2), "stable",
               "Atteinte à la marque Ulta Beauty en cas d'incident produit, de problème de service en magasin ou de controverse sur les partenaires ; les réseaux sociaux amplifient rapidement les retours négatifs."),
            mk("Cybersécurité et données clients Ultamate Rewards", "technological", 3,
               R_MAT.format(n=3), "deteriorating",
               "Programme de fidélité de plus de 40 millions de membres : violation de données, intrusion sur les paiements ou panne IT exposent à des coûts de remédiation, à des amendes et à une perte de confiance."),
            mk("Conformité réglementaire et fiscale multi-États", "regulatory", 2,
               R_GEN.format(n=2), "stable",
               "Évolutions législatives sur la composition des cosmétiques, la protection des consommateurs, la fiscalité d'État et les règles du travail augmentent les coûts de conformité du réseau de magasins."),
        ],
    },
    "UNH": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-02-27 (exercice clos décembre 2024)",
        "risks": [
            mk("Réglementation des assureurs santé et taux Medicare Advantage", "regulatory", 4,
               R_MAT.format(n=4), "deteriorating",
               "Forte dépendance aux décisions des CMS sur les taux Medicare Advantage, les Star Ratings et les règles de remboursement Medicaid : toute réduction de taux ou réforme structurelle affecte directement la rentabilité."),
            mk("Coûts médicaux et antisélection", "financial", 4,
               R_MAT.format(n=4), "deteriorating",
               "Hausse de l'utilisation des soins et antisélection sur les populations couvertes pèsent sur le medical care ratio ; mauvaise tarification ou réserves insuffisantes peuvent dégrader le résultat technique."),
            mk("Cybersécurité et continuité des systèmes Change Healthcare", "technological", 4,
               R_MAT.format(n=4), "deteriorating",
               "Suite à l'incident cyber Change Healthcare, exposition aux intrusions, à la perte de données patients et à la responsabilité civile ; toute défaillance IT majeure perturbe paiements et opérations clients."),
            mk("Contentieux, enquêtes antitrust et conformité", "regulatory", 3,
               R_MAT.format(n=3), "deteriorating",
               "Litiges sur la facturation, enquêtes du DOJ sur les pratiques Medicare Advantage et examens antitrust limitent la capacité d'acquisition et augmentent les coûts juridiques."),
            mk("Concurrence sur les marchés santé commerciaux", "competitive", 3,
               R_GEN.format(n=3), "stable",
               "Concurrence intense de CVS/Aetna, Elevance, Cigna et nouveaux entrants tech sur les segments employer-sponsored, Medicare Advantage et services PBM, pressant tarifs et marges."),
            mk("Intégration Optum et exécution stratégique", "operational", 3,
               R_MAT.format(n=3), "stable",
               "Croissance rapide d'Optum Health et Optum Rx via acquisitions : risques d'intégration, de rétention de praticiens et de réalisation des synergies attendues."),
        ],
    },
    "UNM": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-02-27 (exercice clos décembre 2024)",
        "risks": [
            mk("Hypothèses actuarielles et réserves long terme", "financial", 4,
               R_MAT.format(n=4), "stable",
               "Réserves d'assurance vie et invalidité long terme sensibles aux hypothèses de mortalité, morbidité, persistance et taux d'actualisation : une révision défavorable peut entraîner des charges significatives."),
            mk("Sensibilité aux taux d'intérêt et au portefeuille investi", "financial", 4,
               R_MAT.format(n=4), "deteriorating",
               "Marges sur les produits long terme dépendent du rendement du portefeuille obligataire : baisse durable des taux ou défauts de crédit affecteraient la rentabilité et la couverture des engagements."),
            mk("Run-off Long Term Care et insuffisance de primes", "financial", 4,
               R_MAT.format(n=4), "stable",
               "Bloc fermé Closed Block Long Term Care présente un risque élevé de gross premium valuation deficiency ; approbations tarifaires des régulateurs d'État incertaines et lentes."),
            mk("Conformité réglementaire assureurs et notations de crédit", "regulatory", 3,
               R_MAT.format(n=3), "stable",
               "Encadrement strict par les régulateurs d'État (NAIC, RBC) et sensibilité aux notations financières S&P, Moody's, AM Best ; toute dégradation pèse sur les ventes en groupe et la collecte."),
            mk("Concurrence sur l'assurance prévoyance collective", "competitive", 2,
               R_GEN.format(n=2), "stable",
               "Marché US de l'assurance prévoyance et invalidité collective concentré, avec pression tarifaire des grands employeurs et concurrence de MetLife, Lincoln, Guardian et The Hartford."),
            mk("Cybersécurité et données assurés", "technological", 3,
               R_MAT.format(n=3), "deteriorating",
               "Volume important de données médicales et financières sensibles : exposition à des intrusions, ransomware ou pannes systèmes amenant interruptions et coûts de notification."),
        ],
    },
    "UNP": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-02-07 (exercice clos décembre 2024)",
        "risks": [
            mk("Volumes ferroviaires et cyclicité économique", "macro", 3,
               R_MAT.format(n=3), "stable",
               "Demande de fret ferroviaire fortement liée aux cycles industriels, agricoles, automobiles et énergétiques : récession ou baisse durable des volumes de charbon et de produits intermodaux pèsent sur les revenus."),
            mk("Réglementation fédérale du fret ferroviaire et tarification", "regulatory", 4,
               R_MAT.format(n=4), "deteriorating",
               "Surveillance accrue du Surface Transportation Board sur les pratiques tarifaires, le service et la concurrence ; toute évolution vers une regulation accrue limiterait la flexibilité de pricing."),
            mk("Sécurité opérationnelle et déraillements", "operational", 4,
               R_MAT.format(n=4), "stable",
               "Risque d'accident ferroviaire grave ou de déraillement avec matières dangereuses : conséquences humaines, environnementales, indemnitaires et réputationnelles potentiellement matérielles."),
            mk("Relations sociales et accords collectifs", "operational", 3,
               R_MAT.format(n=3), "stable",
               "Force de travail majoritairement syndiquée : tensions, grèves ou renégociations défavorables des conventions nationales augmentent les coûts de main-d'œuvre et perturbent les opérations."),
            mk("Volatilité du prix du carburant diesel", "financial", 2,
               R_GEN.format(n=2), "stable",
               "Exposition au prix du diesel partiellement répercutée via les surcharges carburant, mais avec un décalage qui peut comprimer temporairement la marge opérationnelle."),
            mk("Cybersécurité des systèmes de contrôle ferroviaire", "technological", 3,
               R_MAT.format(n=3), "deteriorating",
               "Dépendance aux systèmes IT et OT (PTC, dispatching, communications) : une cyberattaque ou panne majeure interromprait le trafic et entraînerait des pertes significatives."),
        ],
    },
    "UPS": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-02-18 (exercice clos décembre 2024)",
        "risks": [
            mk("Concurrence du e-commerce et insourcing Amazon", "competitive", 4,
               R_MAT.format(n=4), "deteriorating",
               "Pression concurrentielle accrue de FedEx, USPS et opérateurs régionaux ; insourcing logistique d'Amazon, principal client historique, réduit les volumes et fragilise les marges domestiques."),
            mk("Cycles économiques et volumes B2B/B2C", "macro", 3,
               R_MAT.format(n=3), "stable",
               "Volumes de colis fortement corrélés à la production industrielle, à la consommation et au commerce international : récession ou ralentissement du fret aérien diminue le chiffre d'affaires."),
            mk("Relations sociales et convention collective Teamsters", "operational", 4,
               R_MAT.format(n=4), "stable",
               "Majorité du personnel US couvert par la convention Teamsters renégociée en 2023 : alourdissement des coûts salariaux pluriannuel et risque de grève à chaque renouvellement."),
            mk("Prix du carburant et de l'énergie", "financial", 2,
               R_GEN.format(n=2), "stable",
               "Exposition aux prix du jet fuel et du diesel partiellement couverte par les surcharges carburant et le hedging, mais variations brutales peuvent peser temporairement sur les marges."),
            mk("Réglementation et transition climatique", "regulatory", 3,
               R_MAT.format(n=3), "deteriorating",
               "Renforcement des normes d'émissions, taxes carbone et obligations de reporting climat dans plusieurs juridictions augmentent les capex de renouvellement de flotte et les coûts d'exploitation."),
            mk("Cybersécurité et continuité opérationnelle", "technological", 3,
               R_MAT.format(n=3), "deteriorating",
               "Dépendance aux systèmes de tri, de tracking et aux plateformes clients : panne IT majeure ou cyberattaque interromprait les flux logistiques et entraînerait des pertes financières immédiates."),
        ],
    },
    "URI": {
        "source": "Item 1A Risk Factors, 10-K déposé 2025-01-29 (exercice clos décembre 2024)",
        "risks": [
            mk("Cyclicité de la construction non résidentielle", "macro", 4,
               R_MAT.format(n=4), "deteriorating",
               "Demande de location d'équipements fortement liée aux dépenses de construction non résidentielle, infrastructure et industrielle : ralentissement cyclique ou hausse des taux freinant les chantiers pèse sur les volumes."),
            mk("Exécution des acquisitions et intégration", "operational", 3,
               R_MAT.format(n=3), "stable",
               "Stratégie de croissance externe (Ahern, Yak) : risques d'intégration, de réalisation des synergies et de surpaiement d'actifs ; dilution potentielle du retour sur capital investi."),
            mk("Endettement et accès au financement", "financial", 3,
               R_MAT.format(n=3), "stable",
               "Dette élevée pour financer la flotte et les acquisitions ; sensibilité aux conditions de marché obligataire et aux refinancings, avec covenants à respecter sur les facilités bancaires."),
            mk("Concurrence locale et nationale fragmentée", "competitive", 2,
               R_GEN.format(n=2), "stable",
               "Marché de la location d'équipements fragmenté avec Sunbelt comme concurrent direct et de nombreux acteurs régionaux : pression sur les tarifs et le taux d'utilisation."),
            mk("Sécurité des chantiers et responsabilité civile", "operational", 3,
               R_MAT.format(n=3), "stable",
               "Activité avec équipements lourds exposée à des accidents sur sites clients : litiges, indemnisations et hausse des primes d'assurance peuvent affecter le résultat."),
            mk("Cybersécurité et plateformes Total Control", "technological", 2,
               R_GEN.format(n=2), "deteriorating",
               "Dépendance à la plateforme digitale Total Control pour la gestion de flotte clients : une intrusion ou panne IT dégraderait la relation client et exposerait à des fuites de données."),
        ],
    },
    "USB": {
        "source": "Item 1 Forward-Looking Statements et Risk Management, 10-K déposé 2025-02-21 (exercice clos décembre 2024) incorporant par référence l'Annual Report 2024",
        "risks": [
            mk("Risque de crédit et qualité du portefeuille de prêts", "financial", 4,
               R_MAT.format(n=4), "deteriorating",
               "Exposition aux pertes sur prêts commerciaux, immobiliers (CRE bureaux notamment) et consommateurs en cas de récession ou de hausse persistante des taux d'intérêt."),
            mk("Risque de taux d'intérêt et marge nette d'intérêt", "financial", 4,
               R_MAT.format(n=4), "stable",
               "Sensibilité du net interest margin à la courbe des taux, au mix dépôts et à la concurrence sur la rémunération de l'épargne ; pivot de la Fed et reprofilage des dépôts non rémunérés affectent la rentabilité."),
            mk("Risque de liquidité et confiance dans le secteur bancaire", "financial", 3,
               R_MAT.format(n=3), "stable",
               "Suite aux faillites de banques régionales de 2023, vigilance accrue sur la composition des dépôts assurés vs non assurés ; un mouvement de fuite des dépôts impacterait la liquidité et le coût du funding."),
            mk("Cybersécurité et fraude paiements", "technological", 4,
               R_MAT.format(n=4), "deteriorating",
               "Banque exposée aux cyberattaques, à la fraude sur les paiements (Elavon, Zelle) et aux pannes des systèmes core : impacts opérationnels, financiers et réputationnels potentiellement matériels."),
            mk("Capital réglementaire et règles Bâle III endgame", "regulatory", 3,
               R_MAT.format(n=3), "deteriorating",
               "Renforcement potentiel des exigences de capital pour les banques de catégorie II suite à l'intégration d'Union Bank ; coûts de conformité accrus et contraintes sur retours actionnaires."),
            mk("Conformité, sanctions et risques juridiques", "regulatory", 3,
               R_GEN.format(n=3), "stable",
               "Examens CFPB, OCC, Fed et procédures CRA peuvent entraîner amendes, restitutions et restrictions opérationnelles ; environnement contentieux dense aux États-Unis."),
        ],
    },
    "UNI.MI": {
        "source": "Rapport annuel 2024 Unipol Assicurazioni, section Risk management policies et Internal Control and Risk Management System",
        "risks": [
            mk("Risque de souscription dommages et santé", "operational", 4,
               R_EU.format(n=4), "deteriorating",
               "Exposition aux sinistres dommages (auto, non-auto, santé) avec sensibilité aux événements climatiques extrêmes en Italie : inondations, grêle, sécheresse peuvent dégrader le combined ratio."),
            mk("Risque de souscription vie et hypothèses actuarielles", "financial", 3,
               R_EU.format(n=3), "stable",
               "Engagements vie sensibles aux hypothèses de mortalité, longévité, lapse et frais ; révisions défavorables peuvent affecter les réserves techniques et le résultat."),
            mk("Risque de marché et de crédit du portefeuille investi", "financial", 4,
               R_EU.format(n=4), "stable",
               "Portefeuille obligataire et actions exposé aux spreads souverains italiens (BTP), à la volatilité des marchés et à la qualité de crédit des émetteurs : Solvency ratio sensible aux mouvements de marché."),
            mk("Solvabilité II et environnement réglementaire", "regulatory", 3,
               R_EU.format(n=3), "stable",
               "Révision en cours du cadre Solvency II (Risk Margin, Cost of Capital) et règles AI Act sur la tarification santé/vie : surcoûts de conformité et contraintes opérationnelles."),
            mk("Intégration de la participation BPER et risques bancassurance", "operational", 3,
               R_EU.format(n=3), "stable",
               "Liens stratégiques avec BPER Banca pour la distribution : exécution de la bancassurance et synergies attendues dépendent de la performance et de la gouvernance du partenaire bancaire."),
            mk("Cybersécurité et continuité des systèmes", "technological", 3,
               R_EU.format(n=3), "deteriorating",
               "Volume de données assurés sensibles : cyberattaques, pannes IT ou compromission des systèmes de souscription et de gestion sinistres affecteraient opérations et réputation."),
        ],
    },
    "UPM.HE": {
        "source": "Rapport annuel 2022 UPM-Kymmene, section Risk management et Sustainability risks",
        "risks": [
            mk("Cyclicité des prix de la pâte et du papier", "macro", 4,
               R_EU.format(n=4), "deteriorating",
               "Forte volatilité des prix de la pâte chimique, du papier graphique et des spécialités : surcapacité asiatique et déclin structurel de la demande papier graphique pèsent sur les revenus."),
            mk("Coûts matières premières, bois et énergie", "operational", 3,
               R_EU.format(n=3), "stable",
               "Sensibilité aux prix du bois finlandais et uruguayen, aux coûts d'énergie et aux produits chimiques : tensions sur l'approvisionnement bois en Finlande après l'arrêt des flux russes."),
            mk("Transition climatique et réglementation forestière", "regulatory", 3,
               R_EU.format(n=3), "deteriorating",
               "Évolutions du paquet Fit for 55, taxonomie UE et règles sur la déforestation (EUDR) imposent investissements et reporting accrus ; risques sur la valorisation des actifs forestiers."),
            mk("Concurrence asiatique et substitution numérique", "competitive", 3,
               R_EU.format(n=3), "deteriorating",
               "Concurrence des producteurs asiatiques sur pâte et emballage, et substitution numérique du papier graphique : besoin de redéploiement vers biofuels, biochemicals et specialty papers."),
            mk("Exécution des grands projets industriels", "operational", 3,
               R_EU.format(n=3), "stable",
               "Démarrage et montée en cadence de l'usine de pâte Paso de los Toros (Uruguay) et des projets bioraffinerie : risques de dépassement budgétaire, retards et performance opérationnelle."),
            mk("Risque de change et exposition internationale", "financial", 2,
               R_EU.format(n=2), "stable",
               "Ventes libellées en USD, EUR et CNY avec coûts en EUR, USD et UYU : volatilité des devises impacte les marges, partiellement couverte par hedging."),
        ],
    },
    "URW.PA": {
        "source": "Rapport annuel 2024 Unibail-Rodamco-Westfield, rapport des commissaires aux comptes et sections risques",
        "risks": [
            mk("Valorisation des actifs immobiliers et taux de capitalisation", "financial", 4,
               R_EU.format(n=4), "deteriorating",
               "Patrimoine de centres commerciaux exposé aux variations des taux de capitalisation : remontée des taux d'intérêt a déjà entraîné des dépréciations significatives, sensibilité forte du LTV."),
            mk("Endettement et refinancement", "financial", 4,
               R_EU.format(n=4), "stable",
               "Dette élevée nécessitant des refinancements réguliers sur marchés obligataires : sensibilité aux spreads de crédit immobilier et aux conditions de marché."),
            mk("Disposal des actifs US Westfield", "operational", 3,
               R_EU.format(n=3), "stable",
               "Programme de cessions du portefeuille US Westfield pour réduire la dette : risque sur la valorisation, le calendrier et la pénalité fiscale de sortie selon les conditions de marché US."),
            mk("Comportement de consommation et concurrence du e-commerce", "macro", 3,
               R_EU.format(n=3), "deteriorating",
               "Fréquentation des centres commerciaux exposée à l'inflation, à la baisse du pouvoir d'achat et à la concurrence structurelle du commerce en ligne, pesant sur les loyers variables et la vacance."),
            mk("Réglementation environnementale et CSRD", "regulatory", 3,
               R_EU.format(n=3), "deteriorating",
               "Obligations CSRD, taxonomie UE et exigences de décarbonation des bâtiments imposent capex de rénovation et reporting détaillé ; risque de stranded assets sur centres non conformes."),
            mk("Risque locatif et concentration des enseignes", "competitive", 3,
               R_EU.format(n=3), "stable",
               "Dépendance à la santé financière des grandes enseignes locataires : faillites ou départs (cf. retraits récents) impactent taux d'occupation et revenus locatifs nets."),
        ],
    },
}

out_dir = "/tmp/risks-batch062"
os.makedirs(out_dir, exist_ok=True)
for ticker, payload in DATA.items():
    obj = {
        "ticker": ticker,
        "risks": payload["risks"],
        "_source": payload["source"],
        "_risks_count": len(payload["risks"]),
        "_risks_signed_by": SIGN,
    }
    with open(os.path.join(out_dir, f"{ticker}.json"), "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"{ticker}: {len(payload['risks'])} risques")
