#!/usr/bin/env python3
"""apply-ghost-fixes-eu5n.py

Apply hero_kpi remap fixes generated by the EU5+N ghost analyzer.

Reads drafts from /tmp/eu5n-ghost-fix-drafts/<TICKER>.json (one per ghost).
By default runs in --dry-run mode : only prints what would change.

Modes
-----
  --dry-run          (default) Show planned edits, write nothing.
  --apply            Actually write src/data/v2-pipeline/<TICKER>.json.
                     Creates <TICKER>.before-ghost-fix.bak.json backup first.
  --force            With --apply, also process drafts flagged
                     requires_yann_validation:true. Without --force, only
                     drafts with requires_yann_validation:false are applied.
  --ticker T         Only process a single ticker (debug).

Safety
------
  * Refuses to run if backup file already exists (no overwrite).
  * Only changes the `hero_kpi` field. No other keys touched.
  * Never deletes anything.
  * Will skip drafts whose suggested_fix is null.
  * Does NOT read or modify src/data/companies/*.json.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

DRAFTS_DIR = Path('/tmp/eu5n-ghost-fix-drafts')
V2_DIR = Path('/Users/yann/spx-app/src/data/v2-pipeline')


def load_drafts(ticker_filter: str | None = None) -> list[dict]:
    drafts: list[dict] = []
    for fp in sorted(DRAFTS_DIR.glob('*.json')):
        if fp.name.startswith('_'):
            continue
        if ticker_filter and fp.stem != ticker_filter:
            continue
        with fp.open() as f:
            drafts.append(json.load(f))
    return drafts


def plan_action(draft: dict, force: bool) -> tuple[str, str]:
    """Return (decision, reason). decision in {'apply','skip','error'}."""
    ticker = draft.get('ticker')
    fix = draft.get('suggested_fix')
    if not fix or not fix.get('new_hero_kpi'):
        return 'skip', 'no suggested_fix (pattern needs re-extraction)'
    if draft.get('requires_yann_validation') and not force:
        return 'skip', 'requires_yann_validation=true (use --force to override)'
    v2_path = V2_DIR / f'{ticker}.json'
    if not v2_path.exists():
        return 'error', f'v2-pipeline file not found : {v2_path}'
    return 'apply', f"set hero_kpi='{fix['new_hero_kpi']}'"


def apply_fix(draft: dict, dry_run: bool) -> None:
    ticker = draft['ticker']
    new_hero = draft['suggested_fix']['new_hero_kpi']
    v2_path = V2_DIR / f'{ticker}.json'
    backup_path = V2_DIR / f'{ticker}.before-ghost-fix.bak.json'

    if dry_run:
        print(f'  DRY-RUN would update {v2_path} hero_kpi → {new_hero!r}')
        return

    if backup_path.exists():
        raise RuntimeError(
            f'Backup already exists for {ticker} : {backup_path} (refusing to overwrite)'
        )

    with v2_path.open() as f:
        data = json.load(f)
    old = data.get('hero_kpi')

    # Sanity guard : ensure new_hero exists as a kpi short
    shorts = [k.get('short') for k in data.get('kpis', [])]
    if new_hero not in shorts:
        raise RuntimeError(
            f"{ticker} : new_hero_kpi {new_hero!r} not found in current kpis "
            f'(shorts={shorts}). Data may have changed since draft was generated.'
        )

    # Write backup
    backup_path.write_text(json.dumps(data, indent=2, ensure_ascii=False))

    data['hero_kpi'] = new_hero
    v2_path.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f'  APPLIED {ticker} : hero_kpi {old!r} → {new_hero!r} (backup: {backup_path.name})')


def main() -> int:
    p = argparse.ArgumentParser()
    g = p.add_mutually_exclusive_group()
    g.add_argument('--dry-run', action='store_true', default=True,
                   help='Show planned edits without writing (default).')
    g.add_argument('--apply', action='store_true',
                   help='Actually write changes.')
    p.add_argument('--force', action='store_true',
                   help='With --apply, also handle drafts marked requires_yann_validation.')
    p.add_argument('--ticker', type=str, default=None,
                   help='Limit to a single ticker (debug).')
    args = p.parse_args()
    dry_run = not args.apply

    if not DRAFTS_DIR.is_dir():
        print(f'Drafts dir missing : {DRAFTS_DIR}', file=sys.stderr)
        return 2

    drafts = load_drafts(args.ticker)
    if not drafts:
        print('No drafts to process.')
        return 0

    print(f'Loaded {len(drafts)} drafts.   mode={"DRY-RUN" if dry_run else "APPLY"}'
          f'   force={args.force}')
    counts = {'apply': 0, 'skip': 0, 'error': 0}
    for draft in drafts:
        ticker = draft.get('ticker', '?')
        decision, reason = plan_action(draft, args.force)
        counts[decision] += 1
        print(f'[{decision:5s}] {ticker:15s} : {reason}')
        if decision == 'apply':
            try:
                apply_fix(draft, dry_run)
            except Exception as exc:
                counts['apply'] -= 1
                counts['error'] += 1
                print(f'  ERROR while applying {ticker}: {exc}', file=sys.stderr)
    print()
    print(f'Summary : apply={counts["apply"]}  skip={counts["skip"]}  error={counts["error"]}')
    if dry_run:
        print('No files were modified (dry-run).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
